name: Build AL Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  build:
    name: Compile and test AL project
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Read AL-Go settings
        id: settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v9.2
        with:
          shell: powershell
          project: .

      - name: Read GitHub secrets
        id: secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v9.2
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'licenseFileUrl,codeSignCertificateUrl,*codeSignCertificatePassword,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString'

      - name: Determine ArtifactUrl
        id: determineArtifactUrl
        uses: microsoft/AL-Go-Actions/DetermineArtifactUrl@v9.2
        with:
          shell: powershell
          project: .

      - name: Build and test
        uses: microsoft/AL-Go-Actions/RunPipeline@v9.2
        env:
          Secrets: ${{ steps.secrets.outputs.Secrets }}
        with:
          shell: powershell
          artifact: ${{ env.artifact }}
          project: .
          buildMode: Default
          token: ${{ github.token }}